### ISSUE TITLE
Major Single Player Hardlock - a20.5b2 EXP

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SphereII/SphereII.Mods#41]
0-S-CORE

NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) FactionManager.DMD<FactionManager::Update>(FactionManager)
  at GameManager.gmUpdate () [0x0012a] in <6a01347f98174dbdb41cb4a4eedf5af7>:0 
  at GameManager.Update () [0x00000] in <6a01347f98174dbdb41cb4a4eedf5af7>:0 
  
  Spammed to the point where it made logs 10mb
  
  When I removed Spherii core it works fine. 
  
  Ironically this issue does not exist when used on a dedicated server and for that I am baffled.

  Using Latest Gitpull for SCore. (At the time of writing this)

**Comment by SphereII** [comment]
Do you have your game log for any of these crashes? I haven't tried Alpha 20.5 yet, but a log file may help.

Also, this looks like it had something to do with Factions. Was this a new save when you added the SCore?

**Comment by P3rf3ctXZer0** [comment]
So that one line text is all you get from log - and yes it has to do with factions module I assume supports the NPCcore mode correct?

**Comment by SphereII** [comment]
Yes, it's to do with a faction patch. Why it's null is confusing.  In the 0-SCore, there is the SCore.dll, and also a pdb file. Is that deployed? That might tell me the line number of the failure.

**Comment by P3rf3ctXZer0** [comment]
I will set up another test environment.

**Comment by P3rf3ctXZer0** [comment]
[output_log_client__2022-05-15__09-54-31.txt](https://github.com/SphereII/SphereII.Mods/files/8695254/output_log_client__2022-05-15__09-54-31.txt)

**Comment by SphereII** [comment]
[0-SCore.zip](https://github.com/SphereII/SphereII.Mods/files/8695320/0-SCore.zip)

Would you mind putting this DLL and pdb file and seeing if the problem goes away?

**Comment by P3rf3ctXZer0** [comment]
> [0-SCore.zip](https://github.com/SphereII/SphereII.Mods/files/8695320/0-SCore.zip)
> 
> Would you mind putting this DLL and pdb file and seeing if the problem goes away?

Sure no problem

**Comment by P3rf3ctXZer0** [comment]
Yes this seems to have fixed it.
