### ISSUE TITLE
Major Issue - MP Dedicated Server a20.5b2 EXP

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SphereII/SphereII.Mods#42]
When using drones the game shows red text and the drones become unusable or even interactive. After removing S-Core drones work entirely as intended. Using Latest Gitpull for SCore. (At the time of writing this)

**Comment by SphereII** [comment]
Do you have log files or any other details about this one?

**Comment by P3rf3ctXZer0** [comment]
No I am sorry but the SP fix seems to have worked.

**Comment by Lloyd233322** [comment]
Как ты его скачал? Куда надо нажимать?
