### ISSUE TITLE
Как скачать мод

### ISSUE THREAD

**Issue by Lloyd233322** [SphereII/SphereII.Mods#54]
Мне нужен этот мод 0-SCore для работы другово мода скажите как это скачать я просто не умею скачивать моды с этого сайта

**Comment by SphereII** [comment]
https://github.com/SphereII/SphereII.Mods/archive/refs/heads/master.zip

**Comment by Lloyd233322** [comment]
Спасибо 🥰🥰🥰 ты самый лучший человек
