### ISSUE TITLE
Hang up after game loaded or started

### ISSUE THREAD

**Issue by Suor** [SphereII/SphereII.Mods#68]
Game runs normally with no mods or with some other mods, but when `0-Score` is added it hangs up immediately after game loaded and you see your hands. Happens both for a new game or continue.

Add log file.

[output_log_client__2023-05-23__21-48-00.txt](https://github.com/SphereII/SphereII.Mods/files/11545543/output_log_client__2023-05-23__21-48-00.txt)

**Comment by Suor** [comment]
Why it's closed?

**Comment by SphereII** [comment]
We are on Alpha 21.1 now. I missed this the first time, but I have no seen any other report from linux users with this error.
