### ISSUE TITLE
Cant repair or upgrade with stone axe while sCore and Locks are enabled

### ISSUE THREAD

**Issue by NexusKnightt** [SphereII/SphereII.Mods#73]
Here is my output log if it helps, whenever i right click to upgrade, i get the error
MissingMethodException: Method not found: int .Inventory.GetItemCount(ItemValue,bool,int,int)

This all happened after A21.1 stable dropped and auto updated

[output_log_client__2023-08-10__19-56-24.txt](https://github.com/SphereII/SphereII.Mods/files/12318028/output_log_client__2023-08-10__19-56-24.txt)

**Comment by SphereII** [comment]
There should be a new version of the score available to fix it.

**Comment by NexusKnightt** [comment]
As suggested, this fixed it. Thanks!
