### ISSUE TITLE
new items scrapping to ingredients 

### ISSUE THREAD

**Issue by Alphaproject1998** [SphereII/SphereII.Mods#89]
For some reason I can't scrap any item that I add after adding this mod without it scrapping them to the ingredients that make up the item, using khzmusik_Polluted_Water & War3zuk FarmLife v3 Enhanced are the most obvious ones as I get unit_iron from baking sheets when it's set to give scrap iron, and for empty jar I get the unit_clay, unit_iron and unit_glass when I should just get broken glass as per the item itself :/

Mods folder when testing:
![explorer_pwWl4Ob27r](https://github.com/SphereII/SphereII.Mods/assets/69695918/948b7ff3-17ee-49b3-8300-0320dd2c985e)

**Comment by SphereII** [comment]
Advanced Item Repair / Scrapping is a feature of the 0-SCore, but it is disabled by default.

	<property name="AdvancedItemRepair" value="false" />

Another mod that you have installed may be changing this to true, and adding in that configuration.

**Comment by Alphaproject1998** [comment]
Thanks a lot, turns out it was turned on some how and I just had to turn it off, not 100% sure how it had it on, most likely me working on the mods I wanted to implement late at night and forgetting about it, thanks a lot, sorry for this, thanks for creating the mods you have made, they are great :)
