### ISSUE TITLE
Not a Issue, have a Question

### ISSUE THREAD

**Issue by BrucemanslandNexus** [SphereII/SphereII.Mods#96]
Hello Spherell, I wanted to ask you if you could make the 1 block crawl feature available to me as a standalone mod? I would then like to publish it in my collection on Nexus and also name you as a creator.

**Comment by BrucemanslandNexus** [comment]
If you explain to me how it works, I'll be happy to do it. I'm not a
modder. This is my first collection.

SphereII ***@***.***> schrieb am Mo., 16. Sept. 2024, 13:37:

**Comment by SphereII** [comment]
I did post score on nexus.   https://www.nexusmods.com/7daystodie/mods/6176

I also posted a One BLock Crouch modlet that requires the 0-SCore.   https://www.nexusmods.com/7daystodie/mods/6177

Feel free to use it, or make a copy of it and change it as needed.

**Comment by BrucemanslandNexus** [comment]
Thank you 😋

SphereII ***@***.***> schrieb am Mi., 18. Sept. 2024, 14:19:
